### PR TITLE
Modified login page

### PR DESCRIPTION
**Pull request by MayankGeek**
Please review it!

### CODE REVIEW

**Comment by MayankGeek** [comment]
Please review it.

**Comment by Rohan-cod** [comment]
Your pr has some conflicts @MayankGeek 
Kindly resolve it first.

**Comment by MayankGeek** [comment]
Can you please tell me how to resolve it because the resolve conflict button is not working?

**Comment by Rohan-cod** [comment]
I'll take care of the conflicts @MayankGeek. 👍

**Comment by MayankGeek** [comment]
I have modified the sign up page please review it and merge it

**Pull request merged**
